config/routes.rb
Rails.application.routes.draw do
  resources :words
  devise_for :users, controllers: { registrations: 'users/registrations' }

  root 'startpage#index'
  post 'role_switch', to: 'startpage#role_switch', as: 'role_switch'

  scope 'admin' do
    resources :users, except: :show
    resources :static_pages, except: :show
  end

  get '/:slug', to: 'static_pages#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
  enum markup_type: { markdown: 'markdown', html: 'html' }

  validates :slug, :markup_type, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :rememberable

  enum role: { member: 0, admin: 1 }

  validates(
    :username,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /^[a-zA-Z0-9_\.]*$/, multiline: true }
  )

  has_many :words

  # Attr and method for login with username or email
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      where(conditions.to_h).find_by(['lower(username) = :value OR lower(email) = :value', { value: login.downcase }])
    elsif conditions.key?(:username) || conditions.key?(:email)
      find_by(conditions.to_h)
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  def authorize_admin
    if user_signed_in?
      return if current_user.admin?
    end

    redirect_to root_path, alert: I18n.t(:admin_rights_needed)
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email language password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def render_not_found
    raise ActionController::RoutingError, 'Not Found'
  end

  private

  def set_locale
    I18n.locale = user_signed_in? ? current_user.language : I18n.default_locale
  end
end

app/controllers/startpage_controller.rb
class StartpageController < ApplicationController
  def index
    @word = Word.all.sample
  end

  def role_switch
    redirect_to root_path unless Rails.env.development?

    current_user.update!(role: params[:role].to_i)

    redirect_back fallback_location: root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authorize_admin, except: :show

  def index
    @static_pages = StaticPage.all
  end

  def show
    page = StaticPage.find_by_slug(params[:slug])

    render_not_found if page.nil?

    @content = if page.markdown?
                 Kramdown::Document.new(page.content).to_html
               else
                 page.content
               end
  end

  def new
    @static_page = StaticPage.new
  end

  def edit
    @static_page = StaticPage.find(params[:id])
  end

  def create
    @static_page = StaticPage.new(static_page_params)

    if @static_page.save
      redirect_to static_pages_path
    else
      render :new
    end
  end

  def update
    @static_page = StaticPage.find(params[:id])

    if @static_page.update(static_page_params)
      redirect_to static_pages_path
    else
      render :edit
    end
  end

  def destroy
    @static_page = StaticPage.find(params[:id])

    @static_page.destroy

    redirect_to static_pages_url
  end

  private

  def static_page_params
    params.require(:static_page).permit(:slug, :content, :markup_type)
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action proc { redirect_to root_path }, only: %i[new create]

    def update
      self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

      resource_updated = update_resource(resource, account_update_params)
      yield resource if block_given?
      if resource_updated
        flash[:notice] = confirmation_notice(account_update_params)
        bypass_sign_in resource, scope: resource_name
        respond_with resource, location: after_update_path_for(resource)
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end

    private

    def confirmation_notice(params)
      I18n.t(:user_saved, locale: params[:language])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to users_path, notice: t(:user_saved)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update(user_params)
      redirect_to users_path, notice: t(:user_saved)
    else
      render :edit
    end
  end

  def destroy
    user = User.find_by_id(params[:id])

    user.destroy

    redirect_to users_path, notice: t(:user_deleted)
  end

  private

  def user_params
    new_params = params.require(:user).permit(:username, :email, :language, :role, :password)

    new_params[:role] = new_params[:role].to_i

    new_params
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_model, only: [:destroy, :update, :show, :edit]
  before_action :authenticate_user!  

  def index
    @words = Word.preload(:user).all.order(created_at: :desc).page params[:page]
  end

  def show
  end

  def new
    @word = Word.new
  end

  def edit
  end

  def create
    @word = Word.new(word_params)

    @word.user = current_user

    if @word.save
      redirect_to @word
    else
      render :new
    end
  end

  def update
    if @word.update(word_params)
      redirect_to @word
    else
      render :edit
    end
  end

  def destroy
    @word.destroy

    redirect_to words_url
  end

  def set_model
    @word = Word.find(params[:id])
  end

  private

  def word_params
    params.require(:word).permit(:text, :creator_id)
  end
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'
        span.sr-only = t(:toggle_navigation)
        span.icon-bar
        span.icon-bar
        span.icon-bar

      = link_to 'MONTAGSMALER', root_path, class: 'navbar-brand'

    #navbar.navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-left
        li = link_to 'Words', words_path


      ul.nav.navbar-nav.navbar-right
        li.dropdown
          - if user_signed_in?
            a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-haspopup='true' aria-expanded='false'
              = current_user.username
              span.caret
            ul.dropdown-menu
              li = link_to t(:logout), destroy_user_session_path, method: :delete
              li = link_to t(:settings), edit_user_registration_path

              - if current_user.admin?
                li.divider role="separator"
                li.dropdown-header = t(:admin)

                li = link_to t(:user_management), users_path
                li = link_to t(:static_pages), static_pages_path

              - if Rails.env.development?
                = render 'layouts/role_switch'

          - else
            = link_to t(:login), new_user_session_path

app/views/layouts/_notice.html.slim
- if notice
  p.alert.alert-success
    = fa_icon 'check-circle', text: notice

    a.close href='#' data-dismiss='alert' aria-label='close'
      | ×

- if alert
  p.alert.alert-danger
    = fa_icon 'exclamation-circle', text: alert

    a.close href='#' data-dismiss='alert' aria-label='close'
      | ×

app/views/layouts/_role_switch.html.slim
li.divider role="separator"
li.dropdown-header = t(:role_switch)

li
  = form_tag role_switch_path, method: 'post'
    = select_tag :role, options_for_select(User.roles, User.roles[current_user.role]), class: 'form-control', onchange: 'this.form.submit()'

app/views/layouts/application.html.slim
html
  head
    title
      | MONTAGSMALER

    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-montagsmalerlinks-track': 'reload'
    = javascript_include_tag 'application', 'data-montagsmalerlinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1"

  body
    .container style='margin-top: 20px;'
      = render 'layouts/navbar'

      = render 'layouts/notice'
      
      .jumbotron
        .container-fluid
          = yield

app/views/startpage/index.html.slim
h1.center = @word.text 

app/views/static_pages/_form.html.slim
.btn-group.pull-right

= simple_form_for @static_page do |f|
  .row
    .col-lg-4
      = f.input :slug
    .col-lg-4
      = f.input :markup_type,
                as: :select,
                label: t(:markup_type),
                collection: StaticPage.markup_types,
                include_blank: false
    .col-lg-4
      br
      .pull-right
        = f.submit t(:save), class: 'btn btn-success'

  br

  .row
    .col-lg-6
      = f.input :content,
                class: 'form-control',
                label: t(:content),
                input_html: { rows: 10, style: 'resize: vertical' }

    label = t(:preview)
    #preview.col-lg-6

app/views/static_pages/edit.html.slim
.page-header
  h1 = t(:edit_static_page)

  .btn-group.pull-right
    = link_to static_pages_path, class: 'btn btn-default' do
      = fa_icon 'list', text: t(:back)

= render 'form'

app/views/static_pages/index.html.slim
.page-header
  h1 = t(:static_pages)

.col-sm-12
  = link_to new_static_page_path, class: 'btn btn-primary pull-right btn-block visible-xs' do
    = fa_icon 'plus', text: t(:new_static_page)
  = link_to new_static_page_path, class: 'btn btn-primary pull-right hidden-xs' do
    = fa_icon 'plus', text: t(:new_static_page)

/.table-responsive <-- use only this if you want your table responsive
/ however dropdowns wont work correctly anymore then
.col-sm-12
  .table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th = t(:slug)
          th = t(:markup_type)
          th
          th.hidden-sm.hidden-xs
      tbody
        - @static_pages.each do | static_page |
          tr
            td
              = static_page.slug
            td
              = static_page.markup_type
            td.hidden-sm.hidden-xs
              = link_to edit_static_page_path(static_page)
                = fa_icon 'pencil', text: t(:edit)
            td.hidden-sm.hidden-xs
              = link_to static_page, method: :delete, data: { confirm: t(:are_you_sure) }
                = fa_icon 'trash', text: t(:delete)

            td.visible-sm.visible-xs
              = fa_icon 'pencil', onclick: "$('#optionModal#{static_page.id}').modal();", style: 'color: #337ab7'

              .modal.modal-vertical-centered.fade aria-labelledby='modal' role='dialog' tabindex='-1' id='optionModal#{static_page.id}'
                .modal-dialog.modal-vertical-centered role='document'
                  .modal-content
                    .modal-body
                      p
                        = button_to edit_static_page_path(static_page), class: 'btn btn-block btn-primary', method: :get
                          = fa_icon 'pencil', text: t(:edit)
                      p
                        = button_to static_page, method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-block btn-danger'
                          = fa_icon 'trash', text: t(:delete)

app/views/static_pages/new.html.slim
.page-header
  h1 = t(:new_static_page)

  = link_to static_pages_path, class: 'btn btn-default pull-right' do
    = fa_icon 'list', text: t(:back)

= render 'form'

app/views/static_pages/show.html.slim
= raw @content

app/views/users/_form.html.slim
= simple_form_for @user, url: @user.new_record? ? users_path : user_path, method: @user.new_record? ? :post : :put do |f|
  .col-lg-4
    = f.input :username
    = f.input :email
    = f.input :language,
              label: t(:language),
              required: true,
              as: :select,
              collection: I18n.available_locales

    = f.input :role, collection: User.roles, label: t(:role), selected: 'member'

    - if @user.new_record?
      = f.input :password, label: t(:password)

    = f.submit t(:save), class: 'btn btn-success'

app/views/users/edit.html.slim
= render 'form'

app/views/users/index.html.slim
h2 = t(:user_management)

.col-sm-12
  = link_to t(:new_user), new_user_path, class: 'btn btn-primary pull-right btn-block visible-xs'
  = link_to t(:new_user), new_user_path, class: 'btn btn-primary pull-right hidden-xs'

.col-sm-12
  .table-responsive
    table.table
      thead
        th = t(:username)
        th = t(:email)
        th = t(:role)
        th.hidden-xs
        th.hidden-xs

      tbody
        - @users.each do |user|
          tr
            td = user.username
            td = user.email
            td = user.role

            td.hidden-sm.hidden-xs = link_to edit_user_path(user)
              = fa_icon 'pencil', text: t(:edit)

            td.hidden-sm.hidden-xs = link_to user_path(user), method: :delete, 'data-confirm' => t(:are_you_sure)
              = fa_icon 'trash', text: t(:delete)

            td.visible-sm.visible-xs
              = fa_icon 'pencil', onclick: "$('#optionModal#{user.id}').modal();", style: 'color: #337ab7'

              .modal.modal-vertical-centered.fade aria-labelledby='modal' role='dialog' tabindex='-1' id='optionModal#{user.id}'
                .modal-dialog.modal-vertical-centered role='document'
                  .modal-content
                    .modal-body
                      p
                        = button_to edit_user_path(user), class: 'btn btn-block btn-primary', method: :get
                          = fa_icon 'pencil', text: t(:edit)
                      p
                        = button_to user, method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-block btn-danger'
                          = fa_icon 'trash', text: t(:delete)

app/views/users/new.html.slim
= render 'form'

app/views/words/_form.html.slim
= simple_form_for @word do |f|
  .col-sm-4
    = f.input :text
    = f.submit t(:save), class: 'btn btn-success'

app/views/words/edit.html.slim
.page-header
  h1 = t(:edit_word)

  .btn-group.pull-right
    = link_to @word, class: 'btn btn-primary' do
      = fa_icon 'info-circle', text: t(:show)

    = link_to words_path, class: 'btn btn-default' do
      = fa_icon 'list', text: t(:back)

= render 'form'

app/views/words/index.html.slim
.page-header
  h1 = t(:words)

.row
  .col-sm-6
    = link_to 'Prev Page', path_to_prev_page(@words), class: 'btn btn-primary', disabled: ['1', nil].include?(params[:page])
    = link_to 'Next Page', path_to_next_page(@words), class: 'btn btn-primary pull-right'

  .col-sm-6
    = link_to new_word_path, style: 'margin-bottom: 10px;', class: 'btn btn-primary pull-right btn-block visible-xs' do
      = fa_icon 'plus', text: t(:new_word)

    = link_to new_word_path, class: 'btn btn-primary pull-right hidden-xs' do
      = fa_icon 'plus', text: t(:new_word)

.row
  .col-sm-12
    .table-responsive
      table.table.table-striped.table-hover
        thead
          tr
            th = t(:text)
            th = t(:creator)
            th
            th.hidden-sm.hidden-xs
            th.hidden-sm.hidden-xs
        tbody
          - @words.each do | word |
            tr
              td
                = word.text
              td
                = word.user.username
              td.hidden-sm.hidden-xs
                = link_to word
                  = fa_icon 'eye', text: t(:show)

              td.hidden-sm.hidden-xs
                = link_to edit_word_path(word)
                  = fa_icon 'pencil', text: t(:edit)

              td.hidden-sm.hidden-xs
                = link_to word, method: :delete, data: { confirm: t(:are_you_sure) }
                  = fa_icon 'trash', text: t(:delete)

              td.visible-sm.visible-xs
                = fa_icon 'pencil', onclick: "$('#optionModal#{word.id}').modal();", style: 'color: #337ab7'

                .modal.modal-vertical-centered.fade aria-labelledby='modal' role='dialog' tabindex='-1' id='optionModal#{word.id}'
                  .modal-dialog.modal-vertical-centered role='document'
                    .modal-content
                      .modal-body
                        p
                          = button_to word, method: :get, class: 'btn btn-block btn-primary'
                            = fa_icon 'eye', text: t(:show)
                        p
                          = button_to edit_word_path(word), class: 'btn btn-block btn-primary', method: :get
                            = fa_icon 'pencil', text: t(:edit)
                        p
                          = button_to word, method: :delete, data: { confirm: t(:are_you_sure) }, class: 'btn btn-block btn-danger'
                            = fa_icon 'trash', text: t(:delete)

app/views/words/new.html.slim
.page-header
  h1 = t(:new_word)

  = link_to words_path, class: 'btn btn-default pull-right' do
    = fa_icon 'list', text: t(:back)

= render 'form'

app/views/words/show.html.slim
.page-header
  h1 = t(:show_word)

  .btn-group.pull-right
    = link_to edit_word_path(@word), class: 'btn btn-primary' do
      = fa_icon 'pencil', text: t(:edit)

    = link_to words_path, class: 'btn btn-default' do
      = fa_icon 'list', text: t(:back)

dl.dl-horizontal
  dt = t(:text)
  dd = @word.text
  dt = t(:creator)
  dd = @word.user.username